export const contentTypes = {
    application: {
        atomXml: 'application/atom+xml',
        ediX12: 'application/EDI-X12',
        edifact: 'application/EDIFACT',
        json: 'application/json',
        javascript: 'application/javascript',
        octetStream: 'application/octet-stream',
        ogg: 'application/ogg',
        pdf: 'application/pdf',
        postscript: 'application/postscript',
        soapXml: 'application/soap+xml',
        fontWoff: 'application/font-woff',
        xhtmlXml: 'application/xhtml+xml',
        xmlDtd: 'application/xml-dtd',
        xopXml: 'application/xop+xml',
        zip: 'application/zip',
        gzip: 'application/gzip',
        xBittorrent: 'application/x-bittorrent',
        xTex: 'application/x-tex',
        xml: 'application/xml',
        msword: 'application/msword',
        xWwwFormUrlencoded: 'application/x-www-form-urlencoded',
        xDvi: 'application/x-dvi',
        xLatex: 'application/x-latex',
        xFontTtf: 'application/x-font-ttf',
        xShockwaveFlash: 'application/x-shockwave-flash',
        xStuffit: 'application/x-stuffit',
        xRarCompressed: 'application/x-rar-compressed',
        xTar: 'application/x-tar',
        xJavascript: 'application/x-javascript',
    },
    audio: {
        basic: 'audio/basic',
        L24: 'audio/L24',
        mp4: 'audio/mp4',
        aac: 'audio/aac',
        mpeg: 'audio/mpeg',
        ogg: 'audio/ogg',
        vorbis: 'audio/vorbis',
        xMsWma: 'audio/x-ms-wma',
        xMsWax: 'audio/x-ms-wax',
        vndRnRealaudio: 'audio/vnd.rn-realaudio',
        vndWave: 'audio/vnd.wave',
        webm: 'audio/webm',
    },
    image: {
        gif: 'image/gif',
        jpeg: 'image/jpeg',
        pjpeg: 'image/pjpeg',
        png: 'image/png',
        svgXml: 'image/svg+xml',
        tiff: 'image/tiff',
        vndMicrosoftIcon: 'image/vnd.microsoft.icon',
        vndWapWbmp: 'image/vnd.wap.wbmp',
        webp: 'image/webp',
    },
    message: {
        http: 'message/http',
        imdnXml: 'message/imdn+xml',
        partial: 'message/partial',
        rfc822: 'message/rfc822',
    },
    model: {
        example: 'model/example',
        iges: 'model/iges',
        mesh: 'model/mesh',
        vrml: 'model/vrml',
        x3dBinary: 'model/x3d+binary',
        x3dVrml: 'model/x3d+vrml',
        x3dXml: 'model/x3d+xml',
    },
    text: {
        cmd: 'text/cmd',
        css: 'text/css',
        csv: 'text/csv',
        html: 'text/html',
        plain: 'text/plain',
        php: 'text/php',
        xml: 'text/xml',
        markdown: 'text/markdown',
        cacheManifest: 'text/cache-manifest',
    },
    video: {
        mpeg: 'video/mpeg',
        mp4: 'video/mp4',
        ogg: 'video/ogg',
        quicktime: 'video/quicktime',
        webm: 'video/webm',
        xMsWmv: 'video/x-ms-wmv',
        xFlv: 'video/x-flv',
        xMsvideo: 'video/x-msvideo',
        threeGpp: 'video/3gpp',
        threeGpp2: 'video/3gpp2',
    },
}
